# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yousif\OneDrive - Wayne State University\School\CSC 4111\EZAudio\EZAudio\downloadlibrary.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadLibrary(object):
    def setupUi(self, DownloadLibrary):
        DownloadLibrary.setObjectName("DownloadLibrary")
        DownloadLibrary.resize(455, 447)
        DownloadLibrary.setStyleSheet("background-color: rgb(74, 74, 74);")
        self.comboBox = QtWidgets.QComboBox(DownloadLibrary)
        self.comboBox.setGeometry(QtCore.QRect(320, 10, 91, 22))
        self.comboBox.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(DownloadLibrary)
        self.groupBox.setGeometry(QtCore.QRect(50, 130, 361, 80))
        self.groupBox.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 81, 51))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../../../../Pictures/rickastley.jpg"))
        self.label_7.setObjectName("label_7")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 20, 41, 53))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 20, 181, 53))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(177, 177, 177);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(177, 177, 177);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(177, 177, 177);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(330, 0, 31, 16))
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(DownloadLibrary)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 40, 361, 80))
        self.groupBox_3.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(10, 20, 81, 51))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("../../../../../Pictures/rickastley.jpg"))
        self.label_36.setObjectName("label_36")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 361, 80))
        self.groupBox_5.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setGeometry(QtCore.QRect(10, 20, 81, 51))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("../../../../../Pictures/joero.png"))
        self.label_37.setObjectName("label_37")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_9.setGeometry(QtCore.QRect(110, 20, 41, 53))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_12.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_12.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_12.addWidget(self.label_40)
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_10.setGeometry(QtCore.QRect(160, 20, 181, 53))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_41.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(177, 177, 177);")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_13.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_42.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(177, 177, 177);")
        self.label_42.setObjectName("label_42")
        self.verticalLayout_13.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_43.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(177, 177, 177);")
        self.label_43.setObjectName("label_43")
        self.verticalLayout_13.addWidget(self.label_43)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(330, 0, 31, 16))
        self.label_8.setObjectName("label_8")
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(110, 20, 41, 53))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_14.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_14.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_14.addWidget(self.label_46)
        self.layoutWidget2 = QtWidgets.QWidget(DownloadLibrary)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layoutWidget3 = QtWidgets.QWidget(DownloadLibrary)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutWidget4 = QtWidgets.QWidget(DownloadLibrary)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")

        self.retranslateUi(DownloadLibrary)
        QtCore.QMetaObject.connectSlotsByName(DownloadLibrary)

    def retranslateUi(self, DownloadLibrary):
        _translate = QtCore.QCoreApplication.translate
        DownloadLibrary.setWindowTitle(_translate("DownloadLibrary", "Download Library"))
        self.comboBox.setItemText(0, _translate("DownloadLibrary", "Sort by Name"))
        self.comboBox.setItemText(1, _translate("DownloadLibrary", "Sort by Channel"))
        self.comboBox.setItemText(2, _translate("DownloadLibrary", "Sort by Date"))
        self.comboBox.setItemText(3, _translate("DownloadLibrary", "Sort by Length"))
        self.groupBox.setTitle(_translate("DownloadLibrary", "Rick Astley - Never Gonna Give You Up (Video)"))
        self.label_4.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Channel</p></body></html>"))
        self.label_5.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Date</p></body></html>"))
        self.label_6.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Length</p></body></html>"))
        self.label.setText(_translate("DownloadLibrary", "Official Rick Astley"))
        self.label_2.setText(_translate("DownloadLibrary", "Oct 25, 2009"))
        self.label_3.setText(_translate("DownloadLibrary", "3:32"))
        self.label_9.setText(_translate("DownloadLibrary", "<html><head/><body><p><a href=\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"><span style=\" text-decoration: underline; color:#0000ff;\">Origin</span></a></p></body></html>"))
        self.groupBox_3.setTitle(_translate("DownloadLibrary", "Rick Astley - Never Gonna Give You Up (Video)"))
        self.groupBox_5.setTitle(_translate("DownloadLibrary", "Joe Rogan Experience #1 - Brian Redban"))
        self.label_38.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Channel</p></body></html>"))
        self.label_39.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Date</p></body></html>"))
        self.label_40.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Length</p></body></html>"))
        self.label_41.setText(_translate("DownloadLibrary", "PowerfulJRE"))
        self.label_42.setText(_translate("DownloadLibrary", "Jan 17, 2013"))
        self.label_43.setText(_translate("DownloadLibrary", "2:02:14"))
        self.label_8.setText(_translate("DownloadLibrary", "<html><head/><body><p><a href=\"https://www.youtube.com/watch?v=ZWBCnvOuXK8\"><span style=\" text-decoration: underline; color:#0000ff;\">Origin</span></a></p></body></html>"))
        self.label_44.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Channel</p></body></html>"))
        self.label_45.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Date</p></body></html>"))
        self.label_46.setText(_translate("DownloadLibrary", "<html><head/><body><p align=\"right\">Length</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DownloadLibrary = QtWidgets.QDialog()
    ui = Ui_DownloadLibrary()
    ui.setupUi(DownloadLibrary)
    DownloadLibrary.show()
    sys.exit(app.exec_())
